# Avant-propos {#sec-avantpropos .unnumbered}

Le présent document a été réalisé avec l'outil Quarto que nous avons utilisé dans la plateforme Visual Studio Code[^avantpropos1]. À partir des sources écrites avec le langage markdown[^avantpropos2] et accessibles dans le répertoire GitHub suivant https://github.com/samszo/HDR, cet outil nous permet de rendre accessible ce document sous différentes formes :

[^avantpropos1]: lien vers l'extension Quarto de Visual Studio Code : <https://quarto.org/docs/get-started/hello/vscode.html>

[^avantpropos2]: Lien vers une explication du langage : <https://docs.framasoft.org/fr/grav/markdown.html>

-   sous la forme d'un fichier PDF : <https://samszo.github.io/HDR/>HDR-SamSzo.pdf

-   sous la forme d'un fichier Word : <https://samszo.github.io/HDR/>HDR-SamSzo.docx

-   sous la forme d'un site Web : <https://samszo.github.io/HDR/>

En consultant ces documents, je vous propose de formaliser vos propres traces et d'exprimer vos points de vue en les rendant facilement accessibles aux autres chercheurs dans une ambition d'ouverture et d'interopérabilité de la science. Pour ce faire, nous vous proposons deux solutions :

-   en utilisant l'outil hypothes.is[^avantpropos3] , vous pouvez annoter directement la version Web de ce travail

-   en utilisant l'outil Zotero, vous pouvez annoter le fichier PDF[^avantpropos4] et rendre accessibles vos ajouts directement dans le groupe Zotero suivant : <https://www.zotero.org/groups/5473429/hdr-samszo>

[^avantpropos3]: Lien vers l'inscription à hypothes.is : <https://web.hypothes.is/sales/>

[^avantpropos4]: Lien vers un tutoriel pour annoter un PDF dans Zotero : <https://zotero.hypotheses.org/1129>

Bonne exploration.