
"La fabrication d'un outil est donc le premier exemple d'un processus mental de modélisation dont le résultat matériel, l'instrument, est un corps solide dont la forme a été dictée par des exigences dynamiques, celles de l'action de l'instrument sur son objet. En ce sens, l'outil n'est guère qu'un verbe solidifié." p. 362
::: {#exergue-PrincipesCarto1 .exergue}
« l'outil n'est guère\
qu'un verbe solidifié »\

[@cardon2015, § 5]
:::


# Concevoir des technologies intellectives pour explorer les écosystème de connaissances {#sec-part-technoIntello}

## Introduction

"La fabrication d'un outil est donc le premier exemple d'un processus mental de modélisation dont le résultat matériel, l'instrument, est un corps solide dont la forme a été dictée par des exigences dynamiques, celles de l'action de l'instrument sur son objet. En ce sens, l'outil n'est guère qu'un verbe solidifié." (Thom, 1975) p. 362

A la manière des sciences dures pour lesquelles les chercheurs bricolent les outils nécessaires à leurs travaux, les sciences humaines disposent elles aussi d'outils spécifiques pour leurs pratiques. Comme en témoigne les listes mises en place par l'ENS pour recenser les outils numériques utilisés par les chercheurs. Toutefois, la particularités de notre approche consiste à développer nos propres outils.

Les avantages d'une telle pratique sont d'avoir à disposition des outils qui répondent très précisément à nos besoins et surtout de pouvoir décider des orientations à prendre dans leurs développements à partir de spécifications établies en temps réel sur la base de nos connaissances et de nos objectifs. Ce qui n'est pas le cas quand il faut rédiger des spécifications détaillées à priori et négocier ensuite avec les ingénieurs des modifications qui sont parfois impossibles à cause des choix de conception non anticipés. L'implémentation de l'algorithme pour calculer la complexité ([1.5.3](#anchor-19) [La complexité existentielle](#anchor-19) p. [51](#anchor-19)) est un bon exemple de la multitude de choix nécessaire pour obtenir les résultats attendus. La majorité de ces choix répondent à des questions posées au moment même du développement de l'algorithme mais qui ne se seraient pas posées si nous avions juste évaluer les résultats et pas la manière de les obtenir.

Les inconvénients de ce type d'approche sont nombreux. Tout d'abord, il faut savoir concevoir, développer et tester un environnement numérique de travail. En d'autre termes, il faut savoir et aimer coder, ce qui n'est pas le cas chez beaucoup de collègues. Ensuite, il faut avoir le temps de se consacrer à cette pratique et accepter que les résultats ne sont pas toujours à la hauteurs des ambitions du départ. Enfin, il peut arriver que les outils répondent uniquement à nos propres besoins et pas à ceux d'une communautés plus large.

Quoi qu'il en soit, il est pour nous toujours aussi stimulant d'inventer de nouveaux outils pour répondre à nos besoins de recherche et par la même les renouveler par la confrontation avec des questions que nous n'avions pas prévues. De plus, ces pratiques de la conception, du développement et du test, nous permettent de transmettre aux étudiants des manières de faire efficaces e les confrontant à des problématiques complexes en prise avec l'actualité technique. Il nous semble que l'humanisme numérique passe par cette confrontation avec les arcanes des machines numériques pour mieux comprendre ce qu'elles sont ou pas.

