::: {#exergue-visees1 .exergue}
« C'est donc à la condition de l'interprétation,\
autrement dit du discernement, \[...\]\
que la guerre, portée par les techniques\
en tant qu'elles sont toujours des armes,\
peut se transformer en lutte politique paisible \[...\]\
dans l'espace d'un droit\
qui est aussi celui d'un nous. »\
[@stiegler2004, p. 35]
:::

::: {#exergue-visees2 .exergue}
« Il faut prendre acte,\
de cette entrée du nombre en politique \[...\],\
relevant d'une mathématisation générale du monde \[...\],, mais aussi comme montée de la raison commerçante,\
vers la raison d'état,\
et comme descente du politique,\
vers la sphère domestique »\
[@berns2009, p. 45]
:::

# Echelles d'exploration et axes d'expérimentation {#sec-visees}

Suite à la présentation de nos positionnements scientifiques @sec-positionnements qui retrace notre parcours depuis nos premières recherches sur les catalogues de vente d'un marchand de gravure au XVIIIe siècles à Paris et sur l'influence de John Cage jusqu'à notre proposition d'un métamodèle pour la modélisation des écosystèmes de connaissances @sec-modeleOntoEthique , nous développons dans ce chapitre nos perspectives scientifiques. Elles s'appuient sur une proposition théorique @sec-principesTheo basée sur:

-   8 principes fondamentaux : dialogique, récursif, hologrammatique, cycle de la sémiose, plis analogiques, raison trajective, degrés de flexibilité, ontoéthique

-   3 pouvoirs existentiels : discerner, raisonner, agir

-   4 dimensions existentielles : physique, actant, concept, rapport

Cette proposition théorique est mises en pratique dans des cartographies de connaissances dont nous définissons les principes de représentations @sec-principesCarto :

-   spatio - temporelle

-   hiérarchique

-   topographique

-   topologique

-   réseau

Nous montrons ici comment déployer ces propositions théoriques et pratiques dans des projets de recherches spécifiques suivant des niveaux d'échelles et des axes d'expérimentations.

L'objectif principal que nous fixons avec ces perspectives de recherche est celui de lutter contre un « amincissement du monde » et une représentation de la pensée qui supprime la multiplicité des modes d'existences :

> « Tout se passe comme si la densité des modes d'existence, la pluralité des relations que nous pouvons entretenir avec les êtres qui forment nos milieux et qu'ils entretiennent entre eux, l'hétérogénéité de nos savoirs, cette « surabondance du réel » était la cible d'un leitmotiv : une seule logique pour l'hétérogénéité des savoirs, un seul mode d'existence pour la pluralité des êtres, un seul cosmos pour la diversité des mondes. Bref, cette peur d'être dupe a pour effet de réduire les savoirs, les êtres et le monde à une seule et unique couche d'existence. » [@debaise2021, § 6]

Ce qui nous importe ici c'est de combattre une « politique de la méfiance »[@guattari1989], réduisant les environnements à une simple ressource en usant de catégories qui rendent équivalentes ou insignifiantes les manières d'habiter, de s'attacher, de valoriser. Ce « laminage des subjectivités » (*Ibid.*) entraîne la destruction des rapports collectifs par une mise en concurrence généralisée à tous les niveaux des individus entre eux. Voyez donc ici l'expression d'une subjectivité qui donnera lieu j'espère à une politique de la curiosité conduisant au développement d'un collectif de pensé stimulé par la différence.

> « De nouveaux outils analytiques sont nécessaires pour étudier la distribution et les liens entre les instruments, les énoncés, les compétences incorporées et, plus généralement, tous les actants mobilisés. Ce sont à la fois les contenus et les modes de circulation de ce qui est produit qui dépendent de la dynamique de ces interactions. » [@callon2013]

## Échelles d'exploration {#sec-echelleExploration}

Examinons tout d'abord nos perspectives de recherche suivant quatre échelles qui correspondent aux quatre dimensions existentielles (physique, actant, concept, rapport) qui composent notre métamodèle d'existence informationnelle @sec-modeleOntoEthique.

Nous exprimons ici une corrélation qui approfondit celles que nous avons déjà présentées, entre dimensions de l'existence et genres de connaissances :

-   physique-choc,

-   actant-dynamique,

-   concept-essence,

-   rapport-potentialité.

La corrélation entre échelles d'exploration et dimensions de l'existence pose la question de savoir en quoi l'exploration d'une dimension de l'existence conditionne l'échelle avec laquelle les phénomènes sont observés. Par exemple, peut-on observer à la même échelle les dimensions physiques et conceptuelles ? Les échelles de chaque dimension sont-elles compatibles les unes avec les autre ?

Nous ne répondrons pas ici à ces questions mais nous poserons simplement les bases d'une réflexion en donnant des exemples d'échelles spécifiques à chaque dimension.

### Échelle locale : produire une expression matérielle cohérente {#sec-echelleLocale}

Cette première échelle est en lien avec la première dimension de l'existence celle des matières physiques. Plus spécifiquement, elle concerne la production de cette dimension en se focalisant sur les conditions d'une expression cohérente des physicalités, c'est-à-dire la production de faits. Nous nommons cette échelle locale, car elle correspond à l'observation la plus en adéquation avec le terrain, à la manière des fouilles archéologiques dont l'objectif est de décrire des traces pour conjecturer des faits. Cette échelle est aussi celle des enquêtes et des entretiens dont il faut capter les significations et construire les interprétations. À cette échelle d'exploration, nous nous intéressons particulièrement aux moyens de transcrire les traces en préservant le plus possible leurs cohérences avec le contexte de l'expression.

Notre objectif est de définir des protocoles simples et efficaces pour récolter ces traces notamment à travers des cartographies sémantiques dont nous avons défini les principes dans les chapitres précédents. Nous avons déjà mis en pratique ce type de recherche [@szoniecky2011; @szoniecky2019; @szoniecky2020], mais souhaitons continuer nos investigations en expérimentant de nouveaux modes d'interactions.

Nous proposons de concevoir des « capteurs sémantiques »[@zacklad2010] plus efficaces et précis pour récolter les pouvoirs @sec-pouvoirAgirCartoAffect d'une existence informationnelle et approfondir les recherches déjà menées [@szoniecky2019b] en définissant les cartographies sémantiques comme des interfaces dynamiques et interactives composées :

-   d'un système de coordonnées conceptuelles pour formaliser une expression interopérable

-   d'une projection des concepts dans un vocabulaire graphique pour visualiser des expressions

-   de dispositifs d'interactions avec l'utilisateur (click, drag & drop, capture de gestes, etc.) pour manipuler des expressions

Ces cartographies prennent comme vocabulaires graphiques ceux des cartographies géographiques, des plans d'habitations ou toute autre forme graphique comme des étoiles, des icônes, des dessins, des schémas, etc. Ce qui importe c'est la capacité de la cartographie de rendre explicite, affordant, les interactions des utilisateurs avec le vocabulaire graphique et la projection de ces interactions dans quatre systèmes de coordonnées :

-   espaces matériels @sec-espaceMateriels

-   espaces conceptuels @sec-espaceConceptuels

-   réseaux d'acteurs @sec-espaceActant

-   temporalités @sec-rapportsInstExis.

Le passage par ces systèmes de coordonnées permet de formaliser l'expression pour la rendre interopérable avec d'autres expressions. Ainsi l'interprétation passe par le positionnement des utilisateurs dans ces quatre systèmes de coordonnées. Positions que l'on peut calculer automatiquement par exemple dans l'espace matériel grâce au GPS ou dans la temporalité́ grâce à la synchronisation des horloges mondiales. En revanche, les positionnements dans le réseau des acteurs et dans les espaces conceptuels nécessitent des interactions avec l'utilisateur.

Par exemple, je souhaite approfondir les questions théoriques autour de la modélisation de l'activité en lien avec les collègues ergonomes du laboratoire Paragraphe. Plus particulièrement, je m'intéresse à la captation du goût à travers un dispositif d'exploration des choix. Entre pouvoirs de discernement et d'agir comment émerge la délibération du goût : j'aime, je n’aime pas, c'est bon, c'est mauvais ? Peut-on modéliser ce processus ? Jusqu'où ? L'enjeu très ambitieux est de questionner en quoi le pragmatisme, c'est-à-dire un choix spécifique à l'acteur ici et maintenant, permet de penser une logique quelques que soit la multiplicité des acteurs ici et maintenant.

### Échelle sociale : la communauté des enseignants chercheurs {#sec-echelleSociale}

Corrélées à la dimension des actants, nous observons à l'échelle sociale les groupes d'individus dans leurs manières d'être ensemble ou non, ce qu'ils génèrent dans les autres dimensions existentielles, comment et pourquoi. Plus particulièrement, ce qui nous intéresse d'observer à cette échelle, c'est la communauté des enseignants-chercheurs (EC). Pas uniquement, les EC professionnels que l'on côtoie à l'université ou dans d'autres centres de recherches, mais tout actant qui explore un domaine, raconte ses explorations et transmet les moyens de les faire soi-même. Je pense notamment aux enseignants du primaire et du secondaire, mais aussi aux formateurs, aux maîtres d'apprentissage et plus largement aux parents proches et plus lointains que nous croisons et qui nous nourrissent de leurs expériences. Je pense aussi aux dispositifs numériques qui eux aussi participent à cette communauté suivant des manières d'être différentes, mais qu'il est important de comprendre à l'heure où les assistants numériques personnels prennent de plus en plus d'importance. Les recherches que nous souhaitons mener à cette échelle concernent la modélisation de cette communauté dans toute sa diversité afin d'analyser en quoi et comment des manières d'être spécifiques influencent la transmission des connaissances.

Par exemple, depuis trois ans, nous travaillons avec des collègues de science de l'éducation et de psychologie sur un projet qui va dans ce sens. Le projet MANEP[^visees-1] [@brasselet2022] vise à mieux comprendre la manière dont l’utilisation des environnements numériques d’apprentissages (ENA) en tant que pratique pédagogique innovante, peut jouer un rôle dans le développement du sentiment de compétence et de la motivation scolaire. Cet objectif est sous-jacent à un questionnement plus large autour des effets des environnements numériques sur les apprentissages : est-ce que ce sont les ENA et le plaisir lié à l’usage d’un écran qui tendent à développer la motivation des élèves ? Sont-ce les ENA qui agissent comme une récompense en soi et qui par leurs modalités plus ludiques agiraient sur la motivation ? Ou encore est-ce un effet de la ludification par interactivité de l’expérience ?

[^visees-1]: la description suivante reprend le dépôt à l'appel à projets de l'INSPE de l'Académie de Lille en 2023

Afin de répondre à ces différentes questions, nous avons étudié l’effet du contexte d’enseignement – avec médiations numérique et humaine - sur la motivation scolaire. Dans la modalité d’enseignement avec médiation humaine, l’enseignant mène la situation d’apprentissage et dans la modalité d’enseignement avec médiation numérique, l’apprentissage est réalisé sous un format numérique sans l’enseignant. L’étude s’est déroulée dans les académies de Lille et Versailles. 129 élèves répartis en quatre classes de CM2 ont participé à une séquence d’apprentissage en résolution de problèmes composée de quatre séances en mode « médiation humaine » et quatre en mode « médiation numérique ». Nous cherchons donc à mieux comprendre le rôle joué par les ENA dans la motivation. Plus particulièrement, nous souhaitons analyser le rôle des feedbacks proposés dans les différentes modalités d’enseignement sur la motivation et le sentiment de compétence scolaires. Est-ce que les feedbacks sont proposés et reçus différemment en fonction de la modalité d’enseignement ?

Nous pensons que ces travaux menés dans un contexte très spécifique peuvent d'éboucher sur des préconisations génériques concernant la modélisation des interactions entre les actants définit comme le cycle réception-\>objectivation-\>expression ou discernement-\>raisonnement-\>action. On pourrait par exemple mesurer la fréquence de ces interactions entre les différents acteurs : enseignant, apprenant, ENA. Dans le cas des interactions entre apprenant et ENA, les interactions sont-elles continuelles et individuelles ? Dans le cas des interactions entre enseignants et apprenants, sont-elles alternatives et surtout collectives ?

Il nous semble que cette ambition de passer d'une recherche sur un terrain spécifique à des préconisations génériques doit nécessairement s'appuyer sur théorisation des modèles de connaissances.

### Échelle conceptuelle : théoriser la modélisation des connaissances {#sec-echelleConcetuelle}

Nous avons détaillé plus avant nos principes de modélisation des connaissances @sec-principesTheo, mais nous pensons que ceux-ci doivent être approfondis pour fournir une alternative qualitative à la théorie de l'information de Shannon [@baltz2010]. C'est là l'objectif principal de cette échelle corrélée à la dimension conceptuelle de l'existence.

Nous considérons la théorie de l'information comme trop partielle, car elle se focalise uniquement sur la dimension matérielle de l'existence sans prendre en compte les dimensions sociales et conceptuelles. Nos propositions tentent de remédier à ce manque en modélisant l'information et la communication par une corrélation entre ontologie et éthique, entre existences et connaissances. Nous avons étayé nos propositions avec des principes scientifiques issus de différentes disciplines des sciences humaines (anthropologie, philosophie, sociologie, géographie, sémiologie, psychologie...), mais il nous reste beaucoup de recherches à mener pour consolider cet édifice théorique et le développer dans les sciences de l'information et de la communication en fournissant des méthodes génériques de modélisation et d'analyse des phénomènes d'information et de communication.

Parmi les points théoriques importants pour la modélisation des connaissances que nous souhaitons questionner dans les prochaines années, il y a par exemple les questions concernant la cohérence des rapports entre les dimensions existentielles. Nous avons établi des contraintes fortes de cohérences des rapports @fig-coherenceRapport pour simplifier nos modèles et faciliter leurs transmissions pédagogiques. Toutefois, il nous semble important d'analyser plus profondément d'autres cohérences et d'expérimenter leur viabilité dans des écosystèmes de connaissances différents. Ce travail nécessite une utilisation plus soutenue des méthodes prétopologiques afin de modéliser plus finement les dimensions conceptuelles de ces écosystèmes expérimentaux. Pour ce faire, nous nous rapprochons de nos collègues mathématiciens afin de bien comprendre les limites de nos approches topologiques. Parallèlement, il nous semble important d'analyser les tentatives similaires de modélisation des sciences humaines comme celles menées par René Thom et Krzysztof Pomian [@petitot1978] pour comprendre en quoi les technologies intellectives émergentes pourraient s'inspirer de ces approches.

### Échelle globale : technologies intellectives {#sec-echelleGlobale}

L'échelle globale est pour nous, l'échelle de la mise en commun des connaissances à travers un réseau d'acteurs. Cette échelle, corrélée à la dimension des rapports et par la même aux autres dimensions existentielles, est pour nous le domaine des technologies intellectives dont l'objectif principal est de concevoir des outils spécifiques pour rendre interopérables et stimuler les connaissances produites par les réseaux d'acteurs.

À la manière des sciences dures par exemple en astrophysique avec le télescope spatial James Web ou en physique avec les accélérateurs de particules, les sciences humaines devraient elles aussi concevoir et mettre à disposition des outils très ambitieux pour leurs pratiques. Même si les prémices de tels outils existent, comme en témoignent les listes mises en place par l'ENS pour recenser les outils numériques utilisés par les chercheurs[^visees-2], ils ne rivalisent pas avec l'ampleur des outils qui ont nécessité des dizaines d'années de travaux pour des centaines de personnes et des milliard de dollars investi pour que les chercheurs conçoivent ces outils nécessaires à leurs travaux.

[^visees-2]: Lien vers l'enquête : <https://www.ens.psl.eu/actualites/acteurs-et-activites-en-humanites-numeriques-l-ens>

Peut-être que la particularité des approches en sciences humaines consiste à développer ses propres outils pour un projet spécifique. Les avantages d'une telle pratique sont d'avoir à disposition des outils qui répondent très précisément à nos besoins et surtout de pouvoir décider des orientations à prendre dans leurs développements à partir de spécifications établies en temps réel sur la base de nos connaissances et de nos objectifs. Ce qui n'est pas le cas quand il faut rédiger des spécifications détaillées à priori et négocier ensuite avec les ingénieurs des modifications qui sont parfois impossibles à cause des choix de conception non anticipés.

Par exemple, l'implémentation de l'algorithme pour calculer la complexité @sec-complexiteExitentielle montre la multitude de choix nécessaires pour obtenir les résultats attendus. La majorité de ces choix répondent à des questions posées au moment même du développement de l'algorithme, mais qui ne se seraient pas posées si nous avions juste évalué les résultats et pas la manière de les obtenir.

Les inconvénients de ce type d'approche sont nombreux. Tout d'abord, il faut savoir concevoir, développer et tester un environnement numérique de travail. En d'autres termes, il faut savoir et aimer coder, ce qui n'est pas le cas chez beaucoup de collègues. Ensuite, il faut avoir le temps de se consacrer à cette pratique et accepter que les résultats ne soient pas toujours à la hauteur des ambitions du départ. Enfin, il peut arriver que les outils répondent uniquement à nos propres besoins et pas à ceux d'une communauté plus large.

Quoi qu'il en soit, il est pour nous toujours aussi stimulant d'inventer de nouveaux outils pour répondre à nos besoins de recherche et par la même les renouveler par la confrontation avec des questions que nous n'avions pas prévues. De plus, ces pratiques de la conception, du développement et du test, nous permettent de transmettre aux étudiants des manières de faire efficaces en les confrontant à des problématiques complexes en prise avec l'actualité technique. Il nous semble que l'humanisme numérique passe par cette confrontation avec les arcanes des machines numériques pour mieux comprendre ce qu'elles sont ou pas.

Concevoir ces technologies est un travail long qui demande de bien comprendre les usages particuliers d'un terrain pour en extraire une généricité opératoire dont l'outil sera la mise en forme. Mais cette capacité à formaliser dans un artefact une solution pour améliorer une activité ne suffit pas à faire un outil, il faut aussi comme la bien montré [@leroi-gourhan1964] que cette forme soit adoptée par une communauté d'utilisateur et cela même si la solution proposée n'est pas la plus adéquate. Il en résulte que de nombreuses expérimentations et collaborations restent à mener pour parvenir à l'adoption de ces outils. Ce sera l'objet du work package "Cartographier les connaissances des chercheurs" dont je suis responsable dans le projet ANR EPISODIAS (Elaborer et Penser les Indicateurs de la Science Ouverte et de la Découvrabilité IA Scientifique) que nous avons déposé cette année en collaboration avec une quinzaine de collègues et faisant suite au projet SoVisu [@reymond2023].

## Axes d'expérimentations {#sec-axeExpe}

Les axes d'expérimentation que nous présentons ici utilisent les échelles d'exploration que nous venons de définir pour étudier un domaine de recherche suivant une perspective spécifique. Ces axes précisent comment les échelles sont mises en pratiques et comment grâce à ces expérimentations, le modèle générique d'existence informationnelle montre ses pertinences et en quoi il doit évoluer pour répondre aux besoins de modélisation des écosystèmes de connaissances.

### Axe Frontières numériques {#sec-axeFrontieres}

Depuis plus de 10 ans, à l'initiative d'Imad Saleh, nous explorons la thématique des frontières numériques afin de mieux comprendre notre environnement peuplé d’une multitude de médias numériques qui se définissent tout d’abord comme des documents inscrits dans un fichier informatique qui recèlent une multitude de formats, d’encodages, de fonctionnalités et d’usages[^visees-3]. Ces fichiers numériquement générés ou numérisés entraînent de nombreuses problématiques liées à leur ingénierie [@saleh2014] dont celle de former des espaces numériques que l’on peut mesurer en kilo, méga, giga ou téraoctets. Ces médias numériques de par leurs dynamismes algorithmiques et leurs capacités de créer des relations entre eux, peuvent être appréhendés comme des systèmes de traitement d’entrées (ressources, images, vidéos, interfaces,…) pour obtenir des résultats en sortie. Ils forment une « concaténation de processus », pas seulement un objet fini, et par la même sont analysable par leurs propriétés :

[^visees-3]: Ce paragraphe reprend l'introduction de notre chapitre d'ouvrage [@saleh2024]

-   Ergonomiques : utilisabilité, maniabilité, …

-   Esthétiques : formes / couleurs / sons, esthésie, sensations, …

-   Utiles : histoire culturelle, profil, matrice sociale, …

-   Métamorphiques : adaptabilité, personnalisation, modulation, …

Avec l’Internet, « comme créateur de frontières », la question des frontières numériques est posée et elle attire actuellement l’attention de plusieurs disciplines : informatique, science de l’information, géographie, sociologie, psychologie, etc. Le numérique impacte toutes les activités humaines et par conséquent les comportements des personnes et leurs liens sociaux avec les autres. Le numérique devient un enjeu primordial pour les états qui veulent maîtriser leurs espaces informationnels. Ainsi se pose la question de l’existence d’une frontière numérique ?

> « Les frontières existent bien en espace numérique, mais elles coïncident rarement avec les frontières terrestres puisque ce sont les responsables de chaque portion d'espace numérique qui en déterminent la nature. » [@perriault2011]

Nous souhaitons donner un cadre théorique pour le concept « frontières numériques » en nous interrogeant sur les problématiques émergentes que le numérique, surtout Internet et son application dans le Web, induit sur la société, l’ensemble des activités humaines et sur les frontières classiques. Trois angles d’analyses sont proposés pour y réfléchir :

-   Le rôle du numérique pour constituer une mémoire collective accessible à tous.
-   Les impacts du numérique sur les frontières classiques d’un état et les manières dont un état gère son espace numérique.
-   Les enjeux du numérique et ses applications sur la ville, l’économie, la connaissance et les savoirs, le social et le socioculturel.

Nous souhaitons poursuivre l'exploration de ces pistes de recherches autour des frontières numériques, car le sujet est très vaste et dépasse une discipline, il est transversal et peut intéresser les chercheurs en Sciences humaines et en informatique. Pour développer les collaborations interdisciplinaires que nous avons déjà mises en place et créer d'autres dynamiques autour ce sujet multifacettes, nous continuerons d'organiser des cycles de conférences et des parutions d'ouvrages.

### Axe Internet des objets {#sec-axeIOT}

Nous collaborons depuis 2016 avec Imad Saleh, Mehdi Ammi et Jean-Max Noyer pour mener à bien des recherches multidisciplinaires sur l'Internet des Objets (Internet of Things - IOT). Ces travaux prennent forme dans des articles[@szoniecky2019c; @szoniecky2020a; @szoniecky2018a], des livres [@saleh2018; @saleh2017], des conférences[^visees-4] et une revue en Open Access[^visees-5]. L'ambition de ces recherches sur cet objet industriel et technologique des objets connectés couvre à la fois des questions concernant la gestion de l’entreprise, l’e-administration, mais aussi des problématiques liées à la gestuelle (podomètre, direction du regard, GPS, etc.). Nous nous intéressons aux :

[^visees-4]: Liens vers les sites de ces conférences :\
    - [https://digitaluses-congress.univ-paris8.fr](https://digitaluses-congress.univ-paris8.fr/E-education-209)\
    - <https://ido2017.sciencesconf.org/>\
    - <https://ido2016.sciencesconf.org/>\

[^visees-5]: Lien vers la revue : <https://www.openscience.fr/Internet-des-objets>

> « champs nouveaux à explorer pour les sciences de l’information et de la communication pour étudier d’une part les enjeux sociétaux de ces nouveaux bouleversements technologiques et numériques et d’autre part analyser si les objets connectés répondent à des besoins d'usagers de plus en plus exigeants en matière de service, de communication et l'information. » [@saleh2017]

Nous souhaitons poursuivre ces investigations en continuant la parution de nouveaux articles dans la revue et en organisant de nouvelles conférences dans le cadre du congrès Digital Tools & Uses. Plus particulièrement, en lien avec nos propres recherches, nous voulons questionner les méthodes de pilotages des objets connectés au niveau global avec les smart cities et au niveau local avec la domotique familiale. Ce qui nous intéresse c'est d'analyser comment rendre accessible la complexité des flux infocommunicationnels de l'IOT afin de rendre son pilotage plus efficace par exemple pour la lutter contre les dérèglements climatiques ou pour préserver la vie privée dans une vision écosystémique. Pour ce faire nous envisageons de mettre en place un protocole d'observation participante à la manière de l'observatoire des jardins[^visees-6] à partir une plateforme d'intelligence collective dont l'objectif serait de préconiser des usages à partir des données collectées et pourquoi pas aider à la définition des politiques publiques.

[^visees-6]: Lien vers une explication du protocole : <https://www.oiseauxdesjardins.fr/index.php?m_id=1127&item=18>

### Axe écritures génératives {#sec-axeGeneratif}

Nous travaillons sur cet axe depuis presque trente ans et nous sommes toujours fascinés par la capacité des dispositifs numériques à générer des informations à partir d'un simple clic. Nous avons retracé cet historique dans la première partie de ce volume @sec-positionnements et présenté des recherches que nous avons consacrées à cet axe avec les projets Litte bot @sec-projetLitteBot et Polemika @sec-projetPolemika . Nous souhaitons continuer ces recherches dans les quatre échelles d'exploration en nous focalisant sur les problématiques concernant l'utilisation parallèle des IA connexionniste et symbolique @sec-principesTheo.

Un des lieux idéal pour mener ses investigations est l'atelier transnational sur les écritures numériques[^visees-7] que nous menons en collaboration avec Laura Shackelford professeur au Rochester Institut of Technology (RIT). Cet atelier[^visees-8] s’inscrit dans le cadre du partenariat international entre ArTeC et le Rochester Institute of Technology (RIT) dont la collaboration relativement à la littérature numérique est déjà ancienne : elle remonte à 2016. Les activités de cet atelier ont débuté avec l’IDEFI CréaTIC et se sont poursuivies dans le cadre d’ArTeC. Ils permettent des échanges hybrides d’étudiants via des mobilités courtes et dans une dynamique collective. Ils sont essentiels à une collaboration effective entre ArTeC et les établissements partenaires. Le modèle de collaboration mis en place par cet atelier est très apprécié au RIT où il est considéré comme un modèle à développer. Laura Shackelford a déjà publié plusieurs articles concernant ce travail dans le journal interne du RIT et un article commun avec les étudiants du MIP a été accepté à la conférence internationale Electronic Literature Organization (https://eliterature.org/elo-history/) et à la conférence internationale Art in the Age of AI (https://3ai-24.sciencesconf.org/). De plus, nous collaborons avec le RIT, L’UQAM (Canada) et l’Université Technologie de Compiègne pour développer de nouveaux partenariats et échanges.

[^visees-7]: Lien vers la présentation de l'atelier sur le site du Center for Engaged Storycraft <https://www.rit.edu/storycraft/projects/transnational-digital-creation-workshop-luniversite-de-paris-8>

[^visees-8]: Ce descriptif reprend la demande faite à l'EUR ArTec en 2023

L'atelier se déroule au 2e semestre et s’appuie sur un cours du Master Mention Humanités Numériques. Il est aussi accessible aux étudiants d’autres Masters comme EC libre. Ce cours aborde les trois dimensions formelles de la textualité numérique : animation / navigation / génération dans une optique de développement Web et traitent, pour chacune, des relations entre le texte et les autres médias visuels. La méthodologie suivie est hybride, une période longue, courant sur tout le semestre, durant laquelle les équipes étudiantes évoluent en distanciel et une semaine de finalisation en présentiel donnant lieu à une mobilité des étudiants du RIT à Paris 8. En début de période, les équipes transnationales sont formées à partir de propositions de projets par les étudiants dans le respect de certaines contraintes techniques et formelles imposées par l’équipe pédagogique. Ces équipes ont vocation à être équilibrées en nombre d’étudiants français / étrangers. Durant le semestre, des vidéoconférences permettent aux étudiants des deux universités de faire connaissance, de définir les équipes et les projets et de faire une présentation de conception avant la semaine intensive. Les étudiants bénéficient de créneaux horaires de suivi et de compléments de cours durant le semestre. Les équipes projet gèrent en interne leur emploi du temps et leur communication, notamment la relation avec les étudiants de l’université partenaire. Un projet GitHub est disponible pour l’atelier où sont mis à disposition les supports de cours et autres matériaux. Les participantes et participants sont incités à communiquer entre eux par mail et par les réseaux sociaux.

L’objectif commun est de maîtriser la gestion d’un projet créatif numérique au sein d’une équipe internationale en mettant en œuvre des méthodologies de communication numérique collaborative synchrones et asynchrones. Cet objectif est le plus important, car peu de formations offrent un tel apprentissage alors que la gestion de projet internationale est aujourd’hui courante dès lors qu’on a un niveau de responsabilité auquel peuvent prétendre les titulaires du master ArTeC. Trois objectifs annexes s'ajoutent à cet objectif principal :

-   L’approche d’un point de vue spécifique sur la textualité numérique

-   Une mise en œuvre pluridisciplinaire de la textualité numérique

-   Une mise en œuvre expérimentale d’outils et techniques spécifiques de conception, création, utilisation des IA connexionniste et symbolique.

Parallèlement, nous souhaitons mener une réflexion plus théorique concernant la générativité d'une écriture en questionnant les pouvoirs existentiels @sec-pouvoirAgirCartoAffect d'une écriture. L'objectif est de modéliser ces pouvoirs non seulement pour des écritures algorithmiques, mais aussi pour des partitions graphiques [@stransky2014] pour dans ce cas montrer comment ces écritures génèrent des activités spécifiques comment des concerts, des chorégraphies, des expositions artistiques, des jeux... Les signatures en bas d'un traité, d'un édit ou d'un projet de construction, nous semblent aussi des exemples très pertinents pour montrer comment une écriture toute simple, juste une ligne, est porteuse d'énormément de pouvoirs.

### Axe design des connaissances {#sec-axeDesignConnaissances}

En lien avec le précédent axe sur les écritures génératives, cet axe a pour ambition de concevoir des outils pour manipuler graphiquement les écosystèmes de connaissances dans des environnements numériques d'apprentissage. Nous souhaitons dans cet axe mettre en situation des potentialités de connaissances afin de nous interroger sur les moyens de concevoir une ergonomie des interfaces cognitives. Plus particulièrement, la problématique du passage d'un usage individuel à un usage collectif, nous semble un point crucial : dans quelle mesure une représentation graphique conçue par un individu pour transmettre des connaissances est effectivement perçue par un collectif ?

Outre les problématiques de transposition didactique [@tasra], ce qui nous intéresse ici c'est la capacité des diagrammes [@jedrzejewski2007] et autres représentations graphiques a effectivement transmettre leurs pouvoirs de discernement, de raisonnement et d'action . Pour étudier ces phénomènes, nous construisons depuis une dizaine d'années une base de connaissances rassemblant les documents graphiques utilisés par des chercheurs pour expliciter un point de leur argumentation. Cette collection contient aujourd'hui plus d'une centaine de documents que nous avons récolté manuellement. Nous souhaitons développer cet axe à la fois en direction d'une automatisation de la récolte des graphiques présents dans les thèses et autres documents scientifiques en nous inspirant des travaux en IA menés à la BNF [@moreux2019] et à partir de corpus constitué avec ISTEX[^visees-9] sur des thématiques correspondant à nos axes de recherche. Dans une autre direction, cette collection de documents sera mise à la disposition des chercheurs et des étudiants pour qu'ils évaluent leurs pouvoirs avec des cribles conceptuels @sec-modeliserCrible. Parallèlement à ces travaux de constitution d'un corpus et d'évaluation collective de celui-ci en faisant appel à la subjectivité des individus, nous questionnerons les capacités des IA à produire des modèles à partir de ces documents et à générer à partir de textes scientifiques des diagrammes :

[^visees-9]: Lien vers l'outil d'extraction de corpus : <https://dl.istex.fr/>

> « Le diagramme, pour ainsi dire, provoque d'abord le désordre et le chaos, en jetant pêle-mêle un régime significatif déjà existant, un ordre sémantico-syntaxique et une organisation optique, pour en tirer une clarté et une précision nouvelles. Cette clarté et cette précision n'appartiennent toutefois pas à une logique de représentation avec ses catégories d'identité, de ressemblance, d'analogie et d'opposition, mais à une "logique de la sensation". » [@voss2019, § 21]

Nous poursuivons ainsi les travaux que nous menons en sémiotique visuelle sur la génération automatique d'affiche de film [@szoniecky2023][^visees-10] qui est aujourd’hui envisageable en exploitant les réseaux antagonistes génératifs ou GANs (Generative Adversarial Network). Les GANs sont des algorithmes d’apprentissage à base de réseaux de neurones artificiels, qui modélisent et imitent une distribution de données : images, texte, sons… [@goodfellow]. Ces GANs possèdent des modes d’existences [@latour2012] et une agentivité [@hörl2012] qui leur sont propres comme en témoignent leurs capacités de discerner, raisonner et s’exprimer [@perera2023] qui en font des créateurs de significations. Analyser en détail ces capacités est impossible, car les spécifications de leurs conceptions ne sont pas disponibles et les milliards de paramètres qu’ils utilisent échappent à la compréhension humaine. En revanche, les GANs sont utiles pour comprendre les cycles de sémioses [@µ2015a] en jeu dans la production d’une signification, dans notre cas une affiche de film. Les GANs agissent comme des miroirs dont on analyse les rapports entre les reflets déformants qu’ils produisent et l’intention signifiante à l’origine de l’échange entre l’humain et la machine. C’est dans ce "dialogue halluciné" [@mineur2022] avec les GANs que la plupart des utilisateurs trouvent un intérêt. L'efficacité des GANs est tributaire d’une discussion avec des humains qui valident la pertinence des réponses et corrigent les erreurs afin de renforcer l’apprentissage machine. Cette étape de supervision utilise des formulaires qui enregistrent par exemple la présence ou non d’une catégorie dans une image quand nous validons notre humanité avec un captcha ou qui sont menées à grande échelle [@perrigo] suivant une éthique à questionner [@habermas2013]. Avec les GANs, le dialogue consiste en un échange entre un utilisateur qui écrit un texte court pour décrire ce qu’il veut (prompt) et l'algorithme qui produit la réponse. Ce dialogue prend la forme d’une discussion quand au fur et à mesure des demandes de l’utilisateur la réponse est modifiée par l’algorithme [@wu; @delsignore2023]. Pour analyser les cycles de sémioses et pour piloter au plus juste les algorithmes, nous utilisons un générateur de prompt qui fonctionne avec une cartographie sémantique modélisée sous la forme d’un graphe de connaissances. Un prompt généré correspond à un parcours spécifique de ce graphe de connaissances ce qui permet de suivre très précisément sa construction sémantique en prenant en compte la totalité du parcours ou en sélectionnant uniquement quelques étapes. Ainsi, il devient possible d’évaluer la pertinence sémantique des réponses générées en comparaison de la sémantique du prompt. Les enjeux de cette recherche sont à la fois une modélisation sémantique des affiches de film, une compréhension de l’agentivité des GANs et la réconciliation de deux branches opposées de l’intelligence artificielle.

[^visees-10]: Ce paragraphe reprend le résumé de notre présentation à la 13e Conférence of the International Association for Visual Semiotics <https://www.utadeo.edu.co/fr/link/aisv-iavs-2023/321569/resumes>

Au fil de cet axe, nous continuons aussi les travaux du projet Arcanes @sec-projetArcanes et plus particulièrement ceux menés en collaboration avec Renée Bourassa et Sylvie Leleu Merviel dans le cadre d'un atelier transnational sur les images trompeuses[^visees-11] qui se multiplies depuis l'accessibilité de plus en plus grande des technologies de deepfake [@bourassa2023] et pour lesquels nous avons besoin de développer de nouvelles modalités d'apprentissage de l'esprit critique.

[^visees-11]: Lien vers le site : <https://imagestrompeuses.arcanes.ca/s/images-trompeuses/faceted-browse/1>

### Axe éthique de la discussion pour l'intelligence collective {#sec-axeFormaConsensus}

Avec cet axe que nous avons commencé à explorer au cours de notre thèse, nous cherchons à définir les conditions d'interopérabilité et de réflexivité d'une conversation créative. Plus précisément, nous nous intéressons aux moyens de modéliser un point de vue pour les rendre interopérables avec d'autres y compris ceux simulés par des IAs. Ce qui est en jeu avec cet axe, c'est à la fois d'analyser les puissances de la norme déployées par les méthodes et les outils du Web sémantique et du Linked Open Data (LOD), mais aussi de construire une éthique de la discussion par une formalisation des échanges ayant pour but l'éducation de l'esprit critique par la stimulation des pouvoirs de discerner, raisonner, agir. Une problématique essentielle de cet axe concerne les effets du pilotage par les données du métier de chercheur en SHS. D'un point de vue éthique, l'enjeu est de stimuler "une formation de la volonté" à travers des règles pratiques d'échanges [@habermas2013, p. 22] afin d'exercer sa "volonté" en tant qu'individu ou qu'institution face à une situation de choix :

> « L'éthique classique, comme d'ailleurs les théories modernes, partent de la question qui s'impose à un individu ayant besoin d'orientation lorsque dans une certaine situation, il se trouve, indécis, devant une tâche à maîtriser pratiquement : comment dois-je me comporter, que dois-je faire ? » (ibid. p. 96).

Contrairement à une volonté politique, la "volonté éthique" ne s'exerce pas sur les physicalités @sec-dimensionMateriels en cherchant par exemple à éliminer les biais inhérents à toutes informations nécessairement inadéquates, mais se pratique dans la dimension des idées @sec-dimensionConceptuels, celle de l'intériorité individuelle ou collective :

> « Tout dans l'existence nous condamnait à n'avoir que des idées inadéquates : nous n'avions ni l'idée de nous même, ni l'idée des corps extérieurs, mais seulement des idées d'affections, indiquant l'effet d'un corps extérieur sur nous. Mais précisément, à partir de cet effet, nous pouvons former l'idée de ce qui est commun à un corps extérieur et au nôtre. Compte tenu des conditions de notre existence, c'est pour nous la seule voie capable de nous mener à une idée adéquate. La première idée adéquate que nous ayons, c'est la notion commune, l'idée de ce "quelque chose de commun". » [@deleuze1968, p. 259]

Pour parvenir à ce "commun", nous avons élaboré une multitude de "jeux de langages" [@wittgenstein1987], de diagrammes [@guattari1989], de dispositifs [@gardies2012]... dont ceux utilisés aujourd'hui par les chercheurs pour produire grâce au numérique une multitude de physicalités, de documents, de données, de ressources. Ce développement exponentiel des physicalités renvoie les chercheurs à deux questions éthiques fondamentales :

-   Comment exercer nos volontés éthiques dans cette noosphère pilotée par des machines ?

-   Peut-on concevoir des documents pilotés par des données dédiés à l'exercice de la volonté éthique ?

Pour mener à bien ses réflexions, dans le cadre du groupe de recherche GENIC[^visees-12] et dans nos enseignements, il nous semble fondamental de distinguer l'éthique de la morale dans une optique de formation à l'esprit critique. Il est nécessaire de bien différencier une démarche éthique qui consiste à connaître ce qu'on est et une démarche morale qui se focalise sur l'acceptabilité sociale de ses actions. Dès lors lorsque Dewey & Tufs confondent moral et éthique en ne distinguant pas le « bon » et le « mauvais » du « bien » et du « mal » ils contribuent à déresponsabiliser l'individu dans son apprentissage de l'esprit critique :

[^visees-12]: Lien vers le carnet hypothèse du groupe : <https://genic.hypotheses.org/>

> « L'éthique est la science qui traite de la conduite en tant que l'on peut dire de celle-ci qu'elle est bonne ou mauvaise, qu'elle engage un jugement en termes de bien ou de mal. » [@dewey2021, § 1]

Cette déresponsabilisation passe aussi par une négation de l'individu et de sa spécificité quand ils excluent le goût comme élément du processus de valorisation :

> « La différence entre le haut et le bas de cette échelle n'est pas une affaire de goût, mais de choix consciemment poursuivi. » [@dewey2021, § 13]

Il nous semble au contraire très important de considérer le goût dans la volonté éthique, car il conditionne l'expression d'une subjectivité et par la même l'émergence d'une conscience de soi nécessaire aux choix. C'est pourquoi travailler à une éthique de la discussion pour l'intelligence collective passe selon nous par une meilleure compréhension du choix d'exercer ou non nos pouvoirs de discerner, de raisonner et d'agir.

### Axe puissances existentielles {#sec-puissanceExistentielle}

Nous avons montré @fig-algoComplexity comment calculer la complexité d'un écosystème de connaissance à partir de la modélisation des existences informationnelles qui le composent. Nous voulons enrichir ce travail de modélisation et d'analyse en visant un quadruple but. Premièrement, nous voulons affiner l'algorithme de calcul en collaboration avec des collègues mathématiciens et informaticiens notamment en termes de performance, mais aussi pour évaluer la pertinence d'une modélisation combinant hiérarchies (dimension physique), topographies (dimension actant), topologies (dimension conceptuelle) et réseaux (dimension rapport). Pour répondre à ces questions de géométrie à n dimensions, des compétences en géométrie différentielle sont nécessaires pour par exemple comprendre en quoi le modèle que nous proposons est une "variété"[^visees-13] et s'il serait utile d'utiliser cette notion et celles qui lui sont liées (cartes, atlas).

[^visees-13]: <https://fr.wikipedia.org/wiki/Vari%C3%A9t%C3%A9_(g%C3%A9om%C3%A9trie)>

Deuxièmement, nous souhaitons mener une réflexion théorique sur les rapports entre complexité et puissances existentielles. En collaboration avec nos collègues ergonomes spécialistes de la modélisation de l'activité, nous nous interrogerons sur la mesure des puissances existentielles déclinées en trois pouvoirs fondamentaux : discerner, raisonner, agir. L'objectif est d'améliorer les analyses de l'activité infocommunicationnelle en complétant celles sur le pouvoir d'agir @sec-pouvoirAgirCartoAffect depuis longtemps mis en pratique avec celles sur le discernement et le raisonnement. Plus particulièrement, pour le pouvoir de raisonner une attention particulièrement sera portée sur l'argumentation [@chateauraynaud2015]. La problématique principale de cette réflexion porte sur la question de savoir dans quelle mesure une modélisation de l'activité permet d'analyser les pouvoirs d'une existence informationnelle dans un écosystème de connaissances ?

Troisièmement, nous souhaitons réfléchir aux possibilités d'utiliser ce modèle alliant complexité et pouvoirs pour simuler les états potentiels d'une existence informationnelle. Les objectifs sont non seulement d'améliorer l'analyse de cette existence, mais aussi de prédire ses évolutions, voir même de recommander quelles dimensions existentielles de cette existence devront être développées pour parvenir à un état particulier. Par exemple, l'idée serait de montrer les différents états possibles pour que l'écosystème de connaissances d'un collégien évolue vers celui d'un boulanger, d'un journaliste, d'un footballeur professionnel ou d'un poète. À cet exemple d'usage individuel, nous pourrions en ajouter une infinité d'autres par exemple des usages collectives pour définir les stratégies d'un territoire ou des usages purement intellectuels pour évaluer les différences entre deux auteurs. Ces évolutions entre un état n d'un écosystème de connaissances et un état n+1 pourraient être représentées sous la forme d'un tableau de bord permettant de définir des objectifs et de suivre leur niveau d'achèvement.

Quatrièmement, nous voulons modéliser la puissance existentielle d'écosystèmes de références pour avoir à disposition des échelles de comparaison entre des existences informationnelles. Par exemple, nous prévoyons de mener une recherche au long cours sur la modélisation existentielle de dispositifs numériques comme Wikipédia ou les services d'IA génératives comme ChatGPT[^visees-14] ou Copilot[^visees-15]. De même, des analyses comparatives entre des institutions seraient sans doute très intéressantes à mener par exemple entre des bibliothèques universitaires, entre des écoles, entre des entreprises... Nous souhaitons mener ce travail en collaboration avec nos collègues de science de gestion dans le cadre d'un séminaire de recherche sur la modélisation des connaissances et à une autre échelle dans les cours de Master sur le Web sémantique et ceux sur l'éthique des écosystèmes numériques.

[^visees-14]: Lien vers le service : <https://chatgpt.com/>

[^visees-15]: Lien vers le service : <https://www.microsoft.com/fr-fr/microsoft-copilot>

Cinquièmement, au-delà des expérimentations, cet axe devra alimenter les réflexions sur la problématique fondamentale de la « disjonction de la connaissance techno-scientifique et de la pensée du sens de l'être » [@petitot1998, p. 16], c'est-à-dire l'idée que les sciences et les techniques qu'elles utilisent, s'opposent aux "disciplines interprétatives" seules capables de donner du sens. Comme le confirme Bruno Bachimont en insistant sur le fait que :

> « L’intelligibilité du numérique comme enjeu est donc la capacité de surmonter la rupture interprétative introduite par le calcul entre l’origine des codes et la destination des résultats. » [@bachimont2020]

Or sur ce point, il nous semble que les propositions deleuzienne d'une ontoéthique que nous reprenons à notre compte @sec-modeleOntoEthique, posent les bases d'une réflexion viable et pertinente pour réconcilier modélisation de la complexité et puissances existentielles, formalisme et espérance. Toutefois, ces propositions doivent être passées au crible d'autres penseurs dont les arguments pourraient on non confirmer nos hypothèses. Nous pensons par exemple à l'usage des trois logiques (classique, intuitionniste et paraconsistante) chez Alain Badiou qui correspond à trois figures de la négation (adversité, médiation et coexistence) et qui conduirait selon nous à l'exercice de trois pouvoirs (discerner, raisonner, agir) dans une pulsation existentielle :

> « Je dirais que l’art de vivre, au sens de l’art d’être dans des dispositions créatives, inventives, c’est l’art de la circulation entre les trois négations » [@badiou2018, p. 128]