## Analyser l'onto-éthique des objets connectés  {#sec-analyserOntoEthique}

l'enjeux des objets connextés et de la médecine est fondamental :

« Cependant comparés à l'évaluation du médicament, des aspects et méthodologies nouvelles émergent : il s'agit d'analyser et d'évaluer l'écosystème global de l'objet connecté considéré, d'analyser des trajectoires de soins et non plus les seuls indicateurs de morbi-mortalité, de prendre en compte « l'usager » à la fois en tant que patient (qualité de vie, amélioration du vécu de la maladie, etc.) et en tant qu'« usager » (évaluation de « l'expérience patient »), d'utiliser des méthodologies dont les délais seraient compatibles avec la vitesse d'évolution très rapide des technologies, où les constantes de temps de la recherche clinique habituelle sont totalement dépassées ou, en tout cas, à questionner. Ces nouveaux moyens de « traitement » du sujet humain rendus possibles par l'essor du numérique, qui se veulent toujours plus innovants, convoquent ainsi la nécessité de recherches interdisciplinaire urgente. » § 3

Lindenmeyer, C., & d'Ortho, M.-P. (2019). L'introduction des objets connectés en médecine. *Hermes, La Revue*, *n° 85*(3), 41‑42.

### Concevoir un protocole d'observation participante

À la manière de l'observatoire des jardins

### Déployer une plateforme d'intelligence collective

En relation avec le travail de recherche d'Amri

### Préconiser des usages éthiques

A partir des données collectées...

Evaluer les impactes des politiques publics

## Éditorialiser les récits scientifiques / fictionnelles