## Capter le choix des goûts véritables {#sec-capterGout}

Parallèlement à ces projets de recherches je souhaite approfondir les questions théoriques autour de la captation du goût à travers un dispositif d'exploration des choix véritables.

Entre pouvoirs de discernement et d'agir comment émerge la délibération du goût : j'aime, j'aime pas, c'est bon, c'est mauvais ?

Peut-on modéliser ce processus ? jusqu'où ?

En quoi cette modélisation participe à la définition des axiomes qui identifient l'univers absolu de la vérité ?

L'enjeux très ambitieux est de questionner en quoi une logique pragmatique c'est-à-dire spécifique à l'acteur ici et maintenant permet de penser une logique classique c'est-à-dire absolument générique quelques que soit la multiplicité des acteurs ici et maintenant.

En tant qu'il génère nécessairement de la multiplicité le vide présent dans tout ensemble transforme le topos spécifique des idées inadéquates en possibilité d'expérimenter l'essence absolue d'une vérité générique.

Peut-on modéliser autre chose que les conditions d'expérimentation ? Peut-on s'inspirer des spiritualité du vide pour créer ces conditions ?