## Développer des outils pour cartographier les connaissances {#sec-developper}

### Consolider le calcul de complexité existentielles

En référence au travaux sur la complexité algorithmique (Perrot, 2022)

### Concevoir des interfaces simples et modulaires

#### pour calculer l'indice de complexité existentielle

#### Pour cartographier le flux des affects

a\) le nombre de ceux qui adhèrent à la conception de l'utilité, de la vérité ou de la beauté valorisant (ou condamnant) un objet ou une pratique donnée ;

b\) le poids social de ces adhérents, selon leur statut, leur fonction, leur prestige, leur notoriété et tout ce qui détermine la capacité d'entraînement dont bénéficie leur jugement sur le jugement général du public ; et

c\) l'intensité de l'adhérence avec laquelle les partisans de cet objet ou de cette pratique sont prêts à en défendre et à en promouvoir les mérites. » (Citton 2008b p. 64)

#### pour modéliser graphique un point de vue écosystémique

#### pour générer des explorations cognitives

#### pour recommander des conversations créatrices

### Mettre en relation avec Omeka S

#### Pourquoi Omeka S ?

Pour le développement Open source de solution générique et la mise en relation d'une communauté de concepteurs et d'utilisateurs.

Une plateforme d'éditorialisation scientifique

Comparaison de [*https://www.orkg.org/*](https://www.orkg.org/)

Et de omeka s

#### Omeka S Comment ?

Concevoir et développer des modules spécifiques en Open Source dans le cadre des cours et des ateliers

### Développer des jeux sérieux pour jardiner les connaissances

#### Annoter collectivement les cours de Gilles Deleuze

Reprendre les travaux déjà fait pour les rendre plus accessible et efficace en collaboration avec les chercheurs de l'INA et leur outil OKAPI.

#### H2ptm 4.0 : nouvelle forme de publication scientifique

Reprendre le descriptif du projet pour ArTec\...

#### Cartographier les bibliothèques du monde

Comment explorer finement les connaissances contenues dans les livres à l'échelle de chaque caractère ?

#### 