# Perspectives et projet de recherche {#sec-part-perspectives}


« De nouveaux outils analytiques sont nécessaires pour étudier la distribution et les liens entre les instruments, les énoncés, les compétences incorporées et, plus généralement, tous les actants mobilisés. Ce sont à la fois les contenus et les modes de circulation de ce qui est produit qui dépendent de la dynamique de ces interactions. » § Callon 2013

Pour évaluer les productions scientifiques :

« Conseils pratiques

Pour concevoir des modalités d'évaluation

Se placer sous l'hypothèse que l'on se situe dans un lieu d'interdiscipline et :

https://linux.how2shout.com/2-ways-to-install-mysql-workbench-on-debian-11-bullseye-linux/

■ Trouver les moyens pour mettre en visibilité les dimensions de l'objet scientifique. On peut soustraire l'objet à la discipline pour l'immerger dans l'espace générique, on touche alors quelque chose comme l'objet-sans-discipline.

■ Repérer les composantes humaines et scientifiques du lieu. Le lieu accueille une « science spéciale » dont le caractère universel est donné par sa relation au Réel ; elle est caractérisée par l'intensité du rapport entre l'humain et le savoir. Veiller à ce qu'humain et savoir prennent une autonomie relative, alors ils ne se transforment plus l'un et l'autre, et emportent ou supportent chacun une part des primitives. Le savoir ne paraît plus directement associé au pouvoir, la relation pensée-savoir prend de la consistance et en retour transforme la notion de pouvoir.

■ Chercher à mesurer l'expansion et la dynamique des concepts, des connaissances et des savoirs, en leur donnant des coordonnées initiales au sein des disciplines. Les concepts eux-mêmes prennent des autonomies relatives, en ce cas, ils ont valeur de symboles autour duquel les disciplines construisent une fiction.

■ Donner de la valeur à la fiction. Elle permet de mesurer la distance entre la découverte et l'invention au-delà d'évaluer la juste distance entre le fait et le concept. Avec la fiction, les connaissances disciplinaires sont réarrangées, en relation entre-elles et avec les savoirs indoctes. Les mouvements sont des successions d'inconfort et de reconception de celles et ceux qui produisent la science et des appareils disciplinaires. » (Schmid & Mambrini-Doudet, 2019a) § 67
